fragment EmployeeCertification on EmployeeCertifications {
  employeeId
  certificationId
  expirationDate
  certification {
    certificationName
    certificationProvider {
      certificatoinProviderId
      certificationProviderName
    }
  }
}
