fragment ReleaseRequest on ReleaseRequests {
  referenceNumber
  managerName
  employeeName
  employeeId
  employeeTitle
  function
  releaseDate
  probability
  releasePercentage
  releaseReason
  leaving
  requestStatus
}
