fragment ResourceRequest on ResourceRequests {
  referenceNumber
  managerName
  function
  title
  startDate
  endDate
  probability
  percentage
  status
  coreTeamMember
  replacement
  replacementFor
  requestsCount
  relatedOpportunity
  comments
  assignedResource
  actualPercentage
}
