query Certifications($cursor: String, $limit: Int!) {
  certifications(cursor: $cursor, limit: $limit) {
    errors {
      ...Error
    }
    data {
      hasMore
      items {
        ...Certfication
        employeeCertifications {
          employeeId
        }
      }
    }
  }
}
