query CertificationsProviders($cursor: String, $limit: Int!) {
  certificationsProviders(cursor: $cursor, limit: $limit) {
    errors {
      field
      message
    }
    data {
      hasMore
      items {
        ...CertificationProvider
      }
    }
  }
}
