query CertificationProvider($certificationProviderId: Int!) {
  certificationProvider(certificationProviderId: $certificationProviderId) {
    errors {
      ...Error
    }
    data {
      ...CertificationProvider
      certifications {
        ...Certfication
      }
    }
  }
}
