name: Build Server

on:
  push:
    branches: [ master ]
    paths: 'server/**'
  pull_request:
    branches: [ master ]
    paths: 'server/**'

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: yarn install
      working-directory: server
    - name: Build
      run: yarn build
      working-directory: server