name: Deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull
          yarn install
          yarn build
          yarn deploy
